In [1]:
"""
test inp: 8*8 here but in reality 1000*1000
#1 @ 1,3: 4x4
#2 @ 3,1: 4x4
#3 @ 5,5: 2x2

test out:
........
...2222.
...2222.
.11XX22.
.11XX22.
.111133.
.111133.
........

"""



In [42]:
data = [ '#1 @ 1,3: 4x4',
'#2 @ 3,1: 4x4',
'#3 @ 5,5: 2x2']

import numpy as np


matrix = np.zeros((8,8))

dict1 = {}
for i in data:
    dict1[i.split(':')[0]] = i.split(':')[1]

print(dict1)
print(matrix)
index_counter = 0
print()
for i in dict1.keys():
    index_counter +=1
    co_ordinates = i.split('@')[1]
    if matrix[int(co_ordinates.split(',')[1])][int(co_ordinates.split(',')[0])] == 0:
        matrix[int(co_ordinates.split(',')[1])][int(co_ordinates.split(',')[0])] = index_counter

print(matrix)
        
        

{'#1 @ 1,3': ' 4x4', '#2 @ 3,1': ' 4x4', '#3 @ 5,5': ' 2x2'}
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 2. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 3. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [31]:
# make a 4x4 matrix given string 4x4
import numpy as np

def makematrix(matrix,printer):
    row = int(matrix.split('x')[0])
    colmn = int(matrix.split('x')[1])
    for i in range(row):
        for j in range(colmn):
            print(printer,end='')
        print()

mat = '4x4'
embed = np.zeros((8,8))
makematrix(embed,mat,"!")

!!!!
!!!!
!!!!
!!!!
