In [1]:
"""
test inp: 8*8 here but in reality 1000*1000
#1 @ 1,3: 4x4
#2 @ 3,1: 4x4
#3 @ 5,5: 2x2

test out:
........
...2222.
...2222.
.11XX22.
.11XX22.
.111133.
.111133.
........

"""



In [15]:
data = [ '#1 @ 1,3: 4x4',
'#2 @ 3,1: 4x4',
'#3 @ 5,5: 2x2']

import numpy as np

def makedem(coordinates,splitter):
    i = co_ordinates.split(splitter)
    print(i)
    j = int(co_ordinates.split(splitter)[0])
    return i,j

matrix = np.zeros((8,8))

dict1 = {}
for i in data:
    dict1[i.split(':')[0]] = i.split(':')[1]

print(dict1)
print(matrix)
index_counter = 0
print()
for i in dict1.keys():
    index_counter +=1
    co_ordinates = i.split('@')[1]
    print((dict1[i]))
    if matrix[makedem(co_ordinates,',')] == 0:
        row,clm = makedem(co_ordinates,',')
        dem1,dem2 = makedem(dict1[i],'x')
        while row < (row+dem1):
            while clm < (dem2+clm):
                matrix[row,clm] = index_counter
                clm +=1
            row+=1

print(matrix)
        
        

{'#1 @ 1,3': ' 4x4', '#2 @ 3,1': ' 4x4', '#3 @ 5,5': ' 2x2'}
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]

 4x4
[' 1', '3']


IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

In [4]:
# make a 4x4 matrix given string 4x4
import numpy as np

def makematrix(matrix,printer):
    row = int(matrix.split('x')[0])
    colmn = int(matrix.split('x')[1])
    for i in range(row):
        for j in range(colmn):
            print(printer,end='')
        print()

mat = '4x4'
embed = np.zeros((8,8))
makematrix(mat,"!")
print(embed[2,3])

!!!!
!!!!
!!!!
!!!!
0.0


In [5]:
a = '2,3'
print(int(a))

ValueError: invalid literal for int() with base 10: '2,3'