In [1]:
"""
input:

1, 1
1, 6
8, 3
3, 4
5, 5
8, 9



output: 

..........
.A........
..........
........C.
...D......
.....E....
.B........
..........
..........
........F.

aaaaa.cccc
aAaaa.cccc
aaaddecccc
aadddeccCc
..dDdeeccc
bb.deEeecc
bBb.eeee..
bbb.eeefff
bbb.eeffff
bbb.ffffFf
"""

"\ninput: dabAcCaCBAcCcaDA\n\ndabAcCaCBAcCcaDA  The first 'cC' is removed.\ndabAaCBAcCcaDA    This creates 'Aa', which is removed.\ndabCBAcCcaDA      Either 'cC' or 'Cc' are removed (the result is the same).\ndabCBAcaDA        No further actions can be taken.\n\noutput: dabCBAcaDA (actully then length of this)\n"

In [25]:
import numpy as np
"""
0 = A. 1=B and so on
"""

data = ['1, 1','1, 6','8, 3','3, 4','5, 5','8, 9']
data = data[0]
data = list(map(int,data.split(',')))

max_length = (9,9)
matrix = np.zeros(max_length)
# print(matrix)
    
counter = 0

for i in range(max_length[0]):
    for j in range(max_length[1]):
        if i == data[1] and j == data[0]:
            matrix[i][j] = counter
            counter +=1

print(matrix)

[[0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [16]:
import string



def printer(data):
    
    counter = 0

    for i in range(max_length[0]):
        for j in range(max_length[1]):
            if i == data[0] and j == data[1]:
                print(string.ascii_uppercase[counter])
                counter +=1

            print('.',end='')
        print()
        
data = ['1, 1','1, 6','8, 3','3, 4','5, 5','8, 9']
printer(data)

.........
.A
........
.........
.........
.........
.........
.........
.........
.........
.........
......A
...
.........
.........
.........
.........
.........
.........
.........
